# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sha256_sum',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
