# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashes', '0002_document_sha256_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='sha256_sum',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='sha256',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
